version: '3.8'

services:
  # Bot Builder AI Application
  bot-builder:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "7860:7860"  # Gradio
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://botbuilder:password@db:5432/bot_builder
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./monitoring:/app/monitoring
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - bot-builder-network

  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=bot_builder
      - POSTGRES_USER=botbuilder
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - bot-builder-network

  # Redis Cache
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - bot-builder-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - bot-builder
    restart: unless-stopped
    networks:
      - bot-builder-network

volumes:
  postgres_data:
  redis_data:

networks:
  bot-builder-network:
    driver: bridge 